language: node_js

node_js:
  - "9"

before_install:
  - printf '_auth = %s\n' "$NPM_AUTH_TOKEN" > ~/.npmrc
  - printf 'email = %s\n' "$NPM_EMAIL" >> ~/.npmrc
  - printf 'always-auth = true\n' >> ~/.npmrc

before_script:
  - npm install

script: npm run deploy

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master