language: node_js

node_js:
  - "10"

before_script:
  - npm install

script: npm run build:dev

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master