language: node_js

node_js:
  - "9"

before_install:
  - printf '//registry.npmjs.org/:_authToken = %s\n' "$NPM_AUTH_TOKEN" > ~/.npmrc
  - git config --global user.email ${GITHUB_EMAIL}
  - git config --global user.name ${GITHUB_USER}
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/jsheng2011/react-library-test.git"

before_script:
  - npm install

script: npm run deploy

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master